"""Cadence Spectre Verilog-A Generator with Explicit Shared Intermediate Nodes.

Generates self-contained, 100% Cadence Spectre & Virtuoso compatible Verilog-A (.va)
models where:
- Unique product terms (cubes) are extracted and assigned to explicit intermediate
  analog wire variables (w_c0, w_c1, ...).
- Shared cubes across outputs are evaluated ONCE and reused directly.
- Standard CMOS DeMorgan inverting NAND/NOR logic is used throughout.
"""

from __future__ import annotations
from typing import Dict, List, Set, Tuple, Any
from pyeda.boolalg.expr import OrOp, AndOp, Variable, Complement, Expression

from ams_optimizer.core.models import INVERTER_EQUIVALENTS, TRANSISTOR_COST


class UnifiedVerilogAEmitter:
    """Generates Cadence Spectre-compliant Verilog-A code with shared intermediate nodes."""

    def __init__(
        self,
        module_name: str,
        input_names: List[str],
        targets: List[str],
        min_exprs: Dict[str, Expression],
        gate_counts: Dict[str, int],
        total_ge: float,
        total_transistors: int,
        total_cells: int,
        threshold_voltage: float = 0.9,
    ):
        self.module_name = module_name
        self.input_names = input_names
        self.targets = targets
        self.min_exprs = min_exprs
        self.gate_counts = gate_counts
        self.total_ge = total_ge
        self.total_transistors = total_transistors
        self.total_cells = total_cells
        self.threshold_voltage = threshold_voltage

    def emit(self) -> str:
        lines: List[str] = []

        # 1. Header with Silicon Metrics
        lines.append('`include "constants.vams"')
        lines.append('`include "disciplines.vams"')
        lines.append("")
        lines.append("// ============================================================================")
        lines.append(f"// Module: {self.module_name}")
        lines.append(f"// Generated by Unified Espresso-MV Silicon Optimizer")
        lines.append(f"// Cadence Spectre & Virtuoso Compatible Verilog-A Model")
        lines.append(f"//")
        lines.append(f"// Silicon Area & Gate Complexity:")
        lines.append(f"//   - Total Standard Cells     : {self.total_cells} cells")
        lines.append(f"//   - Inverter Equivalents (GE): {self.total_ge:.1f} GE (1 GE = 1 Inverter = 2 Transistors)")
        lines.append(f"//   - Est. Transistor Count    : {self.total_transistors} transistors")
        lines.append(f"//")
        lines.append(f"// Architecture:")
        lines.append(f"//   - Multi-output shared intermediate nodes (w_c*) evaluated once")
        lines.append(f"//   - Native CMOS DeMorgan inverting NAND-NAND topology")
        lines.append(f"//")
        lines.append(f"// Standard Cell Bill of Materials:")
        for g, cnt in sorted(self.gate_counts.items(), key=lambda x: -x[1]):
            ge_per = INVERTER_EQUIVALENTS.get(g, 3.0)
            tr_per = TRANSISTOR_COST.get(g, 6)
            lines.append(f"//   - {g:<8}: {cnt:>3} cells ({cnt * ge_per:>5.1f} GE, {cnt * tr_per:>4} transistors)")
        lines.append("// ============================================================================")
        lines.append("")

        # 2. Module Declaration & Ports
        ports = [
            "VDD", "VSS", "sub", "res_n", "c_DfT_en_LP", "c_DfT_en_PWM",
            "c_DfT_oc_dig_VDD", "en_LP", "oc_select", "oc_ctrl_cp", "oc_ctrl_bgr",
            "clk_i", "en_lowFreq", "oc_select_ext", "oc_ctrl_cp_ext", "en_LP_ext",
            "c_metalFix_invert_oc_defaults"
        ]
        lines.append(f"module {self.module_name} ({', '.join(ports)});")
        lines.append("  input VDD; electrical VDD;")
        lines.append("  input VSS; electrical VSS;")
        lines.append("  input sub; electrical sub;")
        lines.append("  input res_n; electrical res_n;")
        lines.append("  input c_DfT_en_LP; electrical c_DfT_en_LP;")
        lines.append("  input c_DfT_en_PWM; electrical c_DfT_en_PWM;")
        lines.append("  input [1:0] c_DfT_oc_dig_VDD; electrical [1:0] c_DfT_oc_dig_VDD;")
        lines.append("  output en_LP; electrical en_LP;")
        lines.append("  output oc_select; electrical oc_select;")
        lines.append("  output oc_ctrl_cp; electrical oc_ctrl_cp;")
        lines.append("  output oc_ctrl_bgr; electrical oc_ctrl_bgr;")
        lines.append("  input clk_i; electrical clk_i;")
        lines.append("  output en_lowFreq; electrical en_lowFreq;")
        lines.append("  output oc_select_ext; electrical oc_select_ext;")
        lines.append("  output oc_ctrl_cp_ext; electrical oc_ctrl_cp_ext;")
        lines.append("  output en_LP_ext; electrical en_LP_ext;")
        lines.append("  input c_metalFix_invert_oc_defaults; electrical c_metalFix_invert_oc_defaults;")
        lines.append("")

        # 3. Parameters
        lines.append(f"  parameter real vth   = {self.threshold_voltage:.3f};")
        lines.append("  parameter real tdel  = 30p;")
        lines.append("  parameter real trise = 30p;")
        lines.append("  parameter real tfall = 30p;")
        lines.append("")

        # 4. Analog Helper Functions
        lines.append("  analog function real INV;")
        lines.append("    input a; real a;")
        lines.append("    INV = !(a > 0.5) ? 1.0 : 0.0;")
        lines.append("  endfunction")
        lines.append("")
        lines.append("  analog function real NAND2;")
        lines.append("    input a, b; real a, b;")
        lines.append("    NAND2 = !((a > 0.5) && (b > 0.5)) ? 1.0 : 0.0;")
        lines.append("  endfunction")
        lines.append("")
        lines.append("  analog function real NAND3;")
        lines.append("    input a, b, c; real a, b, c;")
        lines.append("    NAND3 = !((a > 0.5) && (b > 0.5) && (c > 0.5)) ? 1.0 : 0.0;")
        lines.append("  endfunction")
        lines.append("")
        lines.append("  analog function real NAND4;")
        lines.append("    input a, b, c, d; real a, b, c, d;")
        lines.append("    NAND4 = !((a > 0.5) && (b > 0.5) && (c > 0.5) && (d > 0.5)) ? 1.0 : 0.0;")
        lines.append("  endfunction")
        lines.append("")
        lines.append("  analog function real MUX2;")
        lines.append("    input s, d0, d1; real s, d0, d1;")
        lines.append("    MUX2 = (s > 0.5) ? d1 : d0;")
        lines.append("  endfunction")
        lines.append("")

        # 5. Extract Unique Cubes & Build Map
        var_names = []
        for inp in self.input_names:
            if inp in ("c_DfT_en_LP", "c_DfT_en_PWM", "c_metalFix_invert_oc_defaults"):
                var_names.append(f"{inp}_in")
            elif "c_DfT_oc_dig_VDD[" in inp:
                bit = inp.split("[")[1].split("]")[0]
                var_names.append(f"c_DfT_oc_dig_VDD_{bit}_in")
            elif "cnt[" in inp:
                bit = inp.split("[")[1].split("]")[0]
                var_names.append(f"cnt_{bit}_q")
            else:
                var_names.append(f"{inp}_q")

        unique_cubes: List[Tuple[str, Any]] = []
        cube_map: Dict[str, int] = {}
        cube_usage: Dict[str, List[str]] = {}

        for tgt in self.targets:
            expr = self.min_exprs.get(tgt)
            if expr is None:
                continue
            if isinstance(expr, OrOp):
                cubes = list(expr.xs)
            elif str(expr) not in ("0", "1"):
                cubes = [expr]
            else:
                cubes = []

            for c in cubes:
                c_str = str(c)
                cube_usage.setdefault(c_str, []).append(tgt)
                if c_str not in cube_map:
                    cube_map[c_str] = len(unique_cubes)
                    unique_cubes.append((c_str, c))

        # 6. Internal Signal Declarations
        lines.append("  // Internal State Registers")
        lines.append("  real oc_ctrl_bgr_q, oc_ctrl_bgr_d;")
        lines.append("  real cnt_0_q, cnt_0_d;")
        lines.append("  real cnt_1_q, cnt_1_d;")
        lines.append("  real cnt_2_q, cnt_2_d;")
        lines.append("  real cnt_3_q, cnt_3_d;")
        lines.append("  real startup_q, startup_d;")
        lines.append("")
        lines.append("  // Primary Input Logic Variables")
        lines.append("  real c_DfT_en_LP_in;")
        lines.append("  real c_DfT_en_PWM_in;")
        lines.append("  real c_DfT_oc_dig_VDD_1_in;")
        lines.append("  real c_DfT_oc_dig_VDD_0_in;")
        lines.append("  real c_metalFix_invert_oc_defaults_in;")
        lines.append("")
        lines.append("  // Input Polarity Inversion Pool Wires")
        lines.append("  real " + ", ".join(f"w_inv_{v}" for v in var_names) + ";")
        lines.append("")
        lines.append(f"  // Shared Intermediate Product Term Nodes ({len(unique_cubes)} unique shared cubes)")
        lines.append("  real " + ", ".join(f"w_c{i}" for i in range(len(unique_cubes))) + ";")
        lines.append("")
        lines.append("  // Combinational Target Evaluation Wires")
        lines.append("  real en_LP_val, en_lowFreq_val, oc_select_val, oc_ctrl_cp_val;")
        lines.append("")

        # 7. Analog Behavior Block
        lines.append("  analog begin")
        lines.append("    @(initial_step) begin")
        lines.append("      oc_ctrl_bgr_q = 1.0;")
        lines.append("      cnt_0_q = 0.0;")
        lines.append("      cnt_1_q = 0.0;")
        lines.append("      cnt_2_q = 0.0;")
        lines.append("      cnt_3_q = 0.0;")
        lines.append("      startup_q = 1.0;")
        lines.append("    end")
        lines.append("")
        lines.append("    // Asynchronous Reset: res_n falling edge")
        lines.append("    @(cross(V(res_n) - vth, -1)) begin")
        lines.append("      oc_ctrl_bgr_q = 1.0;")
        lines.append("      cnt_0_q = 0.0;")
        lines.append("      cnt_1_q = 0.0;")
        lines.append("      cnt_2_q = 0.0;")
        lines.append("      cnt_3_q = 0.0;")
        lines.append("      startup_q = 1.0;")
        lines.append("    end")
        lines.append("")
        lines.append("    // Clock Edge Register Capture")
        lines.append("    @(cross(V(clk_i) - vth, +1)) begin")
        lines.append("      if (V(res_n) > vth) begin")
        lines.append("        oc_ctrl_bgr_q = (oc_ctrl_bgr_d > 0.5) ? 1.0 : 0.0;")
        lines.append("        cnt_0_q       = (cnt_0_d > 0.5) ? 1.0 : 0.0;")
        lines.append("        cnt_1_q       = (cnt_1_d > 0.5) ? 1.0 : 0.0;")
        lines.append("        cnt_2_q       = (cnt_2_d > 0.5) ? 1.0 : 0.0;")
        lines.append("        cnt_3_q       = (cnt_3_d > 0.5) ? 1.0 : 0.0;")
        lines.append("        startup_q     = (startup_d > 0.5) ? 1.0 : 0.0;")
        lines.append("      end")
        lines.append("    end")
        lines.append("")
        lines.append("    // Primary Input Level Conversions")
        lines.append("    c_DfT_en_LP_in                   = (V(c_DfT_en_LP) > V(VDD,VSS)*0.5) ? 1.0 : 0.0;")
        lines.append("    c_DfT_en_PWM_in                  = (V(c_DfT_en_PWM) > V(VDD,VSS)*0.5) ? 1.0 : 0.0;")
        lines.append("    c_DfT_oc_dig_VDD_1_in            = (V(c_DfT_oc_dig_VDD[1]) > V(VDD,VSS)*0.5) ? 1.0 : 0.0;")
        lines.append("    c_DfT_oc_dig_VDD_0_in            = (V(c_DfT_oc_dig_VDD[0]) > V(VDD,VSS)*0.5) ? 1.0 : 0.0;")
        lines.append("    c_metalFix_invert_oc_defaults_in = (V(c_metalFix_invert_oc_defaults) > V(VDD,VSS)*0.5) ? 1.0 : 0.0;")
        lines.append("")

        # 8. Input Inverter Pool Evaluations
        lines.append("    // -------------------------------------------------------------------------")
        lines.append("    // 1. Global Input & Register Polarity Inversion Pool")
        lines.append("    // -------------------------------------------------------------------------")
        for v in var_names:
            lines.append(f"    w_inv_{v:<32} = INV({v});")
        lines.append("")

        # 9. Shared Intermediate Product Term Evaluations
        lines.append("    // -------------------------------------------------------------------------")
        lines.append(f"    // 2. Shared Intermediate Product Terms ({len(unique_cubes)} unique CMOS NAND gates)")
        lines.append("    //    Terms shared across multiple outputs are evaluated ONCE and reused.")
        lines.append("    // -------------------------------------------------------------------------")

        for idx, (c_str, c_expr) in enumerate(unique_cubes):
            users = cube_usage.get(c_str, [])
            user_comment = f"// Shared: {', '.join(users)}" if len(users) > 1 else f"// Output: {users[0]}"

            if isinstance(c_expr, AndOp):
                lits = []
                for l in c_expr.xs:
                    if isinstance(l, Complement):
                        var_idx = int(str(l.top).split("_")[1])
                        lits.append(f"w_inv_{var_names[var_idx]}")
                    else:
                        var_idx = int(str(l).split("_")[1])
                        lits.append(var_names[var_idx])

                nand_expr = self._build_nand_tree(lits)
                lines.append(f"    w_c{idx:<2} = {nand_expr};  {user_comment}")
            elif isinstance(c_expr, Complement):
                var_idx = int(str(c_expr.top).split("_")[1])
                lines.append(f"    w_c{idx:<2} = {var_names[var_idx]};  {user_comment} (direct literal)")
            elif isinstance(c_expr, Variable):
                var_idx = int(str(c_expr).split("_")[1])
                lines.append(f"    w_c{idx:<2} = w_inv_{var_names[var_idx]};  {user_comment} (inverted literal)")

        lines.append("")

        # 10. Output Combinations (DeMorgan Second-Stage NAND Trees)
        lines.append("    // -------------------------------------------------------------------------")
        lines.append("    // 3. Output Stage Combinational Logic (DeMorgan NAND Trees of Shared Nodes)")
        lines.append("    // -------------------------------------------------------------------------")

        target_va_map = {
            "en_LP": "en_LP_val",
            "oc_select": "oc_select_val",
            "oc_ctrl_cp": "oc_ctrl_cp_val",
            "en_lowFreq": "en_lowFreq_val",
            "oc_ctrl_bgr_d": "oc_ctrl_bgr_d",
            "cnt[3]_d": "cnt_3_d",
            "cnt[2]_d": "cnt_2_d",
            "cnt[1]_d": "cnt_1_d",
            "cnt[0]_d": "cnt_0_d",
            "startup_d": "startup_d",
        }

        for tgt in self.targets:
            va_var = target_va_map.get(tgt, f"{tgt}_val")
            expr = self.min_exprs.get(tgt)
            if expr is None:
                continue

            if str(expr) == "0":
                lines.append(f"    {va_var:<15} = 0.0;")
            elif str(expr) == "1":
                lines.append(f"    {va_var:<15} = 1.0;")
            elif isinstance(expr, OrOp):
                inputs_to_nand = [f"w_c{cube_map[str(c)]}" for c in expr.xs]
                out_expr = self._build_nand_tree(inputs_to_nand)
                lines.append(f"    {va_var:<15} = {out_expr};")
            else:
                c_idx = cube_map[str(expr)]
                lines.append(f"    {va_var:<15} = INV(w_c{c_idx});")

        lines.append("")
        lines.append("    // Analog Electrical Output Drivers")
        lines.append("    V(en_LP)           <+ transition((en_LP_val > 0.5) ? V(VDD) : V(VSS), tdel, trise, tfall);")
        lines.append("    V(oc_select)       <+ transition((oc_select_val > 0.5) ? V(VDD) : V(VSS), tdel, trise, tfall);")
        lines.append("    V(oc_ctrl_cp)      <+ transition((oc_ctrl_cp_val > 0.5) ? V(VDD) : V(VSS), tdel, trise, tfall);")
        lines.append("    V(oc_ctrl_bgr)     <+ transition((oc_ctrl_bgr_q > 0.5) ? V(VDD) : V(VSS), tdel, trise, tfall);")
        lines.append("    V(en_lowFreq)      <+ transition((en_lowFreq_val > 0.5) ? V(VDD) : V(VSS), tdel, trise, tfall);")
        lines.append("    V(oc_select_ext)   <+ transition((oc_select_val > 0.5) ? V(VDD) : V(VSS), tdel, trise, tfall);")
        lines.append("    V(oc_ctrl_cp_ext)  <+ transition((oc_ctrl_cp_val > 0.5) ? V(VDD) : V(VSS), tdel, trise, tfall);")
        lines.append("    V(en_LP_ext)       <+ transition((en_LP_val > 0.5) ? V(VDD) : V(VSS), tdel, trise, tfall);")
        lines.append("  end")
        lines.append("endmodule")
        lines.append("")

        return "\n".join(lines)

    def _build_nand_tree(self, inputs: List[str]) -> str:
        """Constructs a clean NAND2/3/4 tree without exceeding 4 inputs per gate."""
        if len(inputs) == 1:
            return f"INV({inputs[0]})"
        elif len(inputs) == 2:
            return f"NAND2({inputs[0]}, {inputs[1]})"
        elif len(inputs) == 3:
            return f"NAND3({inputs[0]}, {inputs[1]}, {inputs[2]})"
        elif len(inputs) == 4:
            return f"NAND4({inputs[0]}, {inputs[1]}, {inputs[2]}, {inputs[3]})"
        else:
            # Tree-split into 4-input chunks
            chunks = []
            for i in range(0, len(inputs), 4):
                group = inputs[i:i+4]
                chunks.append(self._build_nand_tree(group))
            # Combine chunk outputs
            inv_chunks = [f"INV({c})" for c in chunks]
            return self._build_nand_tree(inv_chunks)
