"""Cadence Spectre Compliant Verilog-A Emitter for Simulation-Driven Synthesis.

Emits pure Cadence Spectre Verilog-A with:
- analog begin ... end
- @(initial_step("static", "ac")) DC operating point initialization
- @(cross(V(clk) - vth, 1, vtol, ttol)) sequential register bank
- Embedded analog gate functions
- 100% output driver contribution coverage with 4-argument transition filters
Compatible with Python 3.9+.
"""

from __future__ import annotations
import re
from typing import Dict, List, Set

from .slicer import SlicedModule, SlicedPort, SlicedRegister
from .cmos_mapper import MappedCone


class VerilogAEmitter:
    """Generates standard Cadence Spectre Verilog-A files."""

    ANALOG_FUNCTIONS = {
        "INV": """  analog function real INV;\n    input a; real a;\n    INV = (a > vth) ? 0.0 : 1.0;\n  endfunction""",
        "NAND2": """  analog function real NAND2;\n    input a, b; real a, b;\n    NAND2 = !( (a > vth) && (b > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "NAND3": """  analog function real NAND3;\n    input a, b, c; real a, b, c;\n    NAND3 = !( (a > vth) && (b > vth) && (c > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "NAND4": """  analog function real NAND4;\n    input a, b, c, d; real a, b, c, d;\n    NAND4 = !( (a > vth) && (b > vth) && (c > vth) && (d > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "NOR2": """  analog function real NOR2;\n    input a, b; real a, b;\n    NOR2 = !( (a > vth) || (b > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "NOR3": """  analog function real NOR3;\n    input a, b, c; real a, b, c;\n    NOR3 = !( (a > vth) || (b > vth) || (c > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "NOR4": """  analog function real NOR4;\n    input a, b, c, d; real a, b, c, d;\n    NOR4 = !( (a > vth) || (b > vth) || (c > vth) || (d > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "AND2": """  analog function real AND2;\n    input a, b; real a, b;\n    AND2 = ( (a > vth) && (b > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "AND3": """  analog function real AND3;\n    input a, b, c; real a, b, c;\n    AND3 = ( (a > vth) && (b > vth) && (c > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "OR2": """  analog function real OR2;\n    input a, b; real a, b;\n    OR2 = ( (a > vth) || (b > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "OR3": """  analog function real OR3;\n    input a, b, c; real a, b, c;\n    OR3 = ( (a > vth) || (b > vth) || (c > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "XOR2": """  analog function real XOR2;\n    input a, b; real a, b;\n    XOR2 = ( (a > vth) ^ (b > vth) ) ? 1.0 : 0.0;\n  endfunction""",
        "MUX2": """  analog function real MUX2;\n    input s, d0, d1; real s, d0, d1;\n    MUX2 = (s > vth) ? ((d1 > vth) ? 1.0 : 0.0) : ((d0 > vth) ? 1.0 : 0.0);\n  endfunction""",
        "AOI21": """  analog function real AOI21;\n    input a, b, c; real a, b, c;\n    AOI21 = !( ((a > vth) && (b > vth)) || (c > vth) ) ? 1.0 : 0.0;\n  endfunction""",
    }

    def __init__(self, supply_voltage: float = 1.8, threshold_voltage: float = 0.9):
        self.vdd = supply_voltage
        self.vth = threshold_voltage

    def emit(
        self,
        mod: SlicedModule,
        mapped_cones: Dict[str, MappedCone],
        used_gates: Set[str],
    ) -> str:
        lines: List[str] = []

        # 1. Header & Standard Includes
        lines.append("// =============================================================================")
        lines.append(f"// Cadence Spectre Verilog-A Model for AMS Digital Block: {mod.module_name}")
        lines.append("// Generated by Simulation-Driven Truth Table Synthesizer")
        lines.append("// =============================================================================")
        lines.append('`include "constants.vams"')
        lines.append('`include "disciplines.vams"')
        lines.append("")

        # 2. Module Header & Port List
        all_port_names = [p.name for p in mod.primary_inputs + mod.primary_outputs]
        lines.append(f"module {mod.module_name}_va ({', '.join(all_port_names)});")
        lines.append("")

        # 3. Port Directions
        for p in mod.primary_inputs + mod.primary_outputs:
            if p.is_vector:
                lines.append(f"  {p.direction} [{p.msb}:{p.lsb}] {p.name};")
            else:
                lines.append(f"  {p.direction} {p.name};")
        lines.append("")

        # 4. Electrical Discipline Declarations (with vector width matching)
        for p in mod.primary_inputs + mod.primary_outputs:
            if p.is_vector:
                lines.append(f"  electrical [{p.msb}:{p.lsb}] {p.name};")
            else:
                lines.append(f"  electrical {p.name};")
        lines.append("")

        # 5. Technology & Timing Parameters
        lines.append("  // ---------------------------------------------------------------------------")
        lines.append("  // Technology & Timing Parameters (Cadence Spectre Compliant)")
        lines.append("  // ---------------------------------------------------------------------------")
        lines.append(f"  parameter real vdd   = {self.vdd};")
        lines.append(f"  parameter real vth   = {self.vth};")
        lines.append("  parameter real tdel  = 10p; // Propagation delay")
        lines.append("  parameter real trise = 10p; // Output rise time")
        lines.append("  parameter real tfall = 10p; // Output fall time")
        lines.append("  parameter real vtol  = 0;   // Voltage tolerance for cross event")
        lines.append("  parameter real ttol  = 0;   // Time tolerance for cross event")
        lines.append("")

        # 6. Analog Functions for Used Gates
        lines.append("  // ---------------------------------------------------------------------------")
        lines.append("  // Custom Analog Standard Cell Gate Functions")
        lines.append("  // ---------------------------------------------------------------------------")
        for g in sorted(used_gates):
            if g in self.ANALOG_FUNCTIONS:
                lines.append(self.ANALOG_FUNCTIONS[g])
                lines.append("")

        # 7. Internal Real Variables
        lines.append("  // ---------------------------------------------------------------------------")
        lines.append("  // Internal State & Combinational Variables")
        lines.append("  // ---------------------------------------------------------------------------")
        sanitized_regs = {r.name: self._sanitize(r.name) for r in mod.registers}
        for rname, san in sanitized_regs.items():
            lines.append(f"  real {san}_q;")
            lines.append(f"  real {san}_d;")

        output_signals = []
        for p in mod.primary_outputs:
            for bit in p.get_bits():
                output_signals.append(bit)
                lines.append(f"  real {self._sanitize(bit)}_val;")
        lines.append("")

        # 8. Main Cadence Verilog-A Analog Block
        lines.append("  // ===========================================================================")
        lines.append("  // Analog Behavioral Block")
        lines.append("  // ===========================================================================")
        lines.append("  analog begin")

        # 8a. Initial Step (DC Operating Point)
        if mod.registers:
            lines.append("    // -------------------------------------------------------------------------")
            lines.append("    // 1. Initial Step: DC Operating Point State Initialization")
            lines.append("    // -------------------------------------------------------------------------")
            lines.append('    @(initial_step("static", "ac")) begin')
            for r in mod.registers:
                san = sanitized_regs[r.name]
                init_val = "1.0" if r.rst_val == 1 else "0.0"
                lines.append(f"      {san}_q = {init_val};")
            lines.append("    end")
            lines.append("")

            # 8b. Sequential Clock Cross Event
            lines.append("    // -------------------------------------------------------------------------")
            lines.append("    // 2. Sequential Clock Cross Event (Register Updates)")
            lines.append("    // -------------------------------------------------------------------------")
            lines.append(f"    @(cross(V({mod.clk_port}) - vth, 1, vtol, ttol)) begin")
            if mod.rst_port:
                rst_cond = f"V({mod.rst_port}) < vth" if mod.rst_active_low else f"V({mod.rst_port}) > vth"
                lines.append(f"      if ({rst_cond}) begin")
                for r in mod.registers:
                    san = sanitized_regs[r.name]
                    init_val = "1.0" if r.rst_val == 1 else "0.0"
                    lines.append(f"        {san}_q = {init_val};")
                lines.append("      end else begin")
                for r in mod.registers:
                    san = sanitized_regs[r.name]
                    lines.append(f"        {san}_q = {san}_d;")
                lines.append("      end")
            else:
                for r in mod.registers:
                    san = sanitized_regs[r.name]
                    lines.append(f"      {san}_q = {san}_d;")
            lines.append("    end")
            lines.append("")

        # 8c. Combinational Logic Cones
        lines.append("    // -------------------------------------------------------------------------")
        lines.append("    // 3. Combinational Logic Cones (Simplified & Tech-Mapped)")
        lines.append("    // -------------------------------------------------------------------------")
        for r in mod.registers:
            san = sanitized_regs[r.name]
            cone_key = f"{r.name}_d"
            expr_str = mapped_cones[cone_key].nested_expression if cone_key in mapped_cones else "0.0"
            va_expr = self._convert_expr_to_va(expr_str, mod, sanitized_regs)
            lines.append(f"    // D-input for DFF {r.name}:")
            lines.append(f"    {san}_d = {va_expr};")

        for out_sig in output_signals:
            san_out = self._sanitize(out_sig)
            expr_str = mapped_cones[out_sig].nested_expression if out_sig in mapped_cones else "0.0"
            va_expr = self._convert_expr_to_va(expr_str, mod, sanitized_regs)
            lines.append(f"    // Output {out_sig}:")
            lines.append(f"    {san_out}_val = {va_expr};")
        lines.append("")

        # 8d. Analog Output Drivers (100% Port Coverage)
        lines.append("    // -------------------------------------------------------------------------")
        lines.append("    // 4. Analog Output Drivers (Continuous Transition Filters)")
        lines.append("    // -------------------------------------------------------------------------")
        for p in mod.primary_outputs:
            for bit in p.get_bits():
                san = self._sanitize(bit)
                lines.append(f"    V({bit}) <+ transition({san}_val * vdd, tdel, trise, tfall);")

        lines.append("  end")
        lines.append("")
        lines.append("endmodule")
        return "\n".join(lines)

    def _sanitize(self, name: str) -> str:
        return re.sub(r"[\[\]]", "_", name).strip("_")

    def _convert_expr_to_va(self, expr: str, mod: SlicedModule, sanitized_regs: Dict[str, str]) -> str:
        s = expr
        # Replace register signals with reg_q
        for rname, san in sorted(sanitized_regs.items(), key=lambda x: len(x[0]), reverse=True):
            if "[" in rname:
                s = s.replace(rname, f"{san}_q")
            else:
                s = re.sub(rf"\b{re.escape(rname)}\b", f"{san}_q", s)

        # Replace primary input signals with V(pin)
        all_in_bits = []
        for p in mod.primary_inputs:
            all_in_bits.extend(p.get_bits())

        for pin in sorted(all_in_bits, key=lambda x: len(x), reverse=True):
            if "[" in pin:
                s = s.replace(pin, f"V({pin})")
            else:
                s = re.sub(rf"\b{re.escape(pin)}\b", f"V({pin})", s)

        return s
