"""Master Multi-Level Logic Optimizer & Synthesizer Pipeline.

Orchestrates multi-level DAG slicing, local truth-table simulation,
exact NPN bitmask matching, Shannon MUX extraction, Quine-McCluskey SOP reduction,
structural logical netlist generation, Cadence Spectre Verilog-A emission,
and Virtuoso SKILL schematic scripts.

Zero external dependencies. Compatible with Python 3.9+.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from .models import (
    SlicedDAG,
    LocalTruthTable,
    MappedLogicNode,
    OptimizationResult,
    StructuralNetlist,
    TRANSISTOR_COST,
    INVERTER_EQUIVALENTS,
)
from .dag_slicer import VerilogDAGSlicer
from .truth_table import LocalTruthTableEvaluator
from .tech_mapper import TechnologyMapper
from .netlist_generator import StructuralNetlistGenerator
from .veriloga_emitter import VerilogAEmitter
from .skill_emitter import SKILLEmitter
from .equivalence_checker import FormalEquivalenceChecker


class AMSOptimizer:
    """High-performance, zero-dependency Multi-Level AMS Digital Optimizer."""

    def __init__(
        self,
        supply_voltage: float = 1.8,
        threshold_voltage: float = 0.9,
        skill_lib: str = "tsmcN65",
        run_verification: bool = True
    ):
        self.supply_voltage = supply_voltage
        self.threshold_voltage = threshold_voltage
        self.skill_lib = skill_lib
        self.run_verification = run_verification

    def run(self, verilog_code: str) -> OptimizationResult:
        # Step 1: Multi-Level Slicing (Preserve intermediate conditions)
        slicer = VerilogDAGSlicer(verilog_code)
        dag = slicer.parse()

        # Step 2: Local Truth Table Simulation & Reachability Analysis
        evaluator = LocalTruthTableEvaluator(dag)

        local_tables: Dict[str, LocalTruthTable] = {}
        for node_name, node in dag.nodes.items():
            local_tables[node_name] = evaluator.evaluate_node(node)

        # Step 3: Technology Mapping (NPN Matching + Shannon MUX + Quine-McCluskey)
        mapper = TechnologyMapper()
        mapped_nodes: Dict[str, MappedLogicNode] = {}
        for node_name in dag.topo_order:
            tt = local_tables.get(node_name)
            if tt:
                mapped_nodes[node_name] = mapper.map_truth_table(tt)

        # Step 4: Generate Intermediate Structural Gate Netlist
        netlist_gen = StructuralNetlistGenerator(dag, mapped_nodes)
        structural_netlist = netlist_gen.generate()

        # Step 5: Aggregate Gate Breakdown, Inverter Equivalents & Transistor Cost
        gate_breakdown: Dict[str, int] = {}
        for inst in structural_netlist.instances:
            gate_breakdown[inst.cell_type] = gate_breakdown.get(inst.cell_type, 0) + 1

        total_gates = structural_netlist.total_gates
        total_ge = structural_netlist.total_inverter_equivalents
        total_transistors = structural_netlist.total_transistors

        # Step 6: Formal Logic Equivalence Checking (LEC)
        equivalence_result = None
        if self.run_verification:
            checker = FormalEquivalenceChecker(dag, mapped_nodes, verilog_code=verilog_code)
            equivalence_result = checker.verify()

        # Step 7: Emit Deliverables (Verilog-A & Virtuoso SKILL)
        va_emitter = VerilogAEmitter(
            dag=dag,
            mapped_nodes=mapped_nodes,
            gate_breakdown=gate_breakdown,
            supply_voltage=self.supply_voltage,
            threshold_voltage=self.threshold_voltage
        )
        veriloga_code = va_emitter.emit()

        skill_emitter = SKILLEmitter(dag, mapped_nodes, self.skill_lib)
        skill_code = skill_emitter.emit()

        # Step 8: Generate Detailed BOM Report with Inverter Equivalents & Verification
        bom_lines = [
            f"# Schematic Bill of Materials (BOM) for `{dag.module_name}`",
            f"",
            f"**Generated by AMS Digital Optimizer (Multi-Level DAG Engine)**",
            f"",
            f"- **Total Gate Count**: {total_gates} cells",
            f"- **Inverter Equivalents (GE)**: {total_ge:.1f} inverters (1 GE = 1 Inverter = 2 Transistors)",
            f"- **Est. Total Transistors**: ~{total_transistors} transistors",
        ]

        if equivalence_result:
            status_str = "100% PASSED (Equivalence Verified)" if equivalence_result.passed else "FAILED (Discrepancy Detected)"
            bom_lines.extend([
                f"- **Formal Equivalence Status**: {status_str}",
                f"- **Verified Vectors**: {equivalence_result.matching_vectors} / {equivalence_result.total_vectors} ({equivalence_result.execution_time_seconds:.4f}s)",
            ])

        bom_lines.extend([
            f"",
            f"| Standard Cell | Count | Inverter Eq. / Cell | Total Inverters | Transistors / Cell | Total Transistors |",
            f"| :--- | :---: | :---: | :---: | :---: | :---: |",
        ])
        for g, cnt in sorted(gate_breakdown.items()):
            ge_per = INVERTER_EQUIVALENTS.get(g, 2.0)
            cost_per = TRANSISTOR_COST.get(g, 6)
            bom_lines.append(f"| `{g}` | {cnt} | {ge_per:.1f} GE | {cnt * ge_per:.1f} inverters | {cost_per}T | {cnt * cost_per}T |")
        bom_lines.append(f"| **TOTAL** | **{total_gates} gates** | — | **{total_ge:.1f} inverters** | — | **~{total_transistors}T** |")
        bom_lines.append(f"")
        bom_lines.append(f"### Simplified Multi-Level Expressions")
        bom_lines.append(f"```verilog")
        for node_name in dag.topo_order:
            mn = mapped_nodes.get(node_name)
            if mn:
                bom_lines.append(f"  {node_name:<24} = {mn.expression};")
        bom_lines.append(f"```")
        bom_report = "\n".join(bom_lines)

        return OptimizationResult(
            module_name=dag.module_name,
            dag=dag,
            mapped_nodes=mapped_nodes,
            structural_netlist=structural_netlist,
            veriloga_code=veriloga_code,
            skill_code=skill_code,
            bom_report=bom_report,
            gate_breakdown=gate_breakdown,
            total_gates=total_gates,
            total_inverter_equivalents=total_ge,
            total_transistors=total_transistors,
            equivalence_result=equivalence_result,
        )
