"""Master Multi-Level Logic Optimizer & Synthesizer Pipeline.

Orchestrates multi-level DAG slicing, local truth-table simulation,
exact NPN bitmask matching, Shannon MUX extraction, Quine-McCluskey SOP reduction,
Cadence Spectre Verilog-A generation, and Virtuoso SKILL schematic scripts.

Zero external dependencies. Compatible with Python 3.9+.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

from .dag_slicer import VerilogDAGSlicer, SlicedDAG
from .truth_table_eval import TruthTableEvaluator, LocalTruthTable
from .npn_mapper import TechnologyMapper, MappedLogicNode, TRANSISTOR_COST
from .veriloga_emitter import VerilogAEmitter
from .skill_emitter import SKILLEmitter


@dataclass
class OptimizationResult:
    module_name: str
    dag: SlicedDAG
    mapped_nodes: Dict[str, MappedLogicNode]
    veriloga_code: str
    skill_code: str
    bom_report: str
    gate_breakdown: Dict[str, int] = field(default_factory=dict)
    total_gates: int = 0
    total_transistors: int = 0


class AMSOptimizer:
    """High-performance, zero-dependency Multi-Level AMS Digital Optimizer."""

    def __init__(self, supply_voltage: float = 1.8, threshold_voltage: float = 0.9, skill_lib: str = "tsmcN65"):
        self.supply_voltage = supply_voltage
        self.threshold_voltage = threshold_voltage
        self.skill_lib = skill_lib

    def run(self, verilog_code: str) -> OptimizationResult:
        # Step 1: Multi-Level Slicing (Preserve intermediate conditions)
        slicer = VerilogDAGSlicer(verilog_code)
        dag = slicer.parse()

        # Step 2: Local Truth Table Simulation & Reachability Analysis
        evaluator = TruthTableEvaluator(dag)
        local_tables: Dict[str, LocalTruthTable] = {}
        for node_name, node in dag.nodes.items():
            local_tables[node_name] = evaluator.evaluate_node(node)

        # Step 3: Technology Mapping (NPN Matching + Shannon MUX + Quine-McCluskey)
        mapper = TechnologyMapper()
        mapped_nodes: Dict[str, MappedLogicNode] = {}
        for node_name in dag.topo_order:
            tt = local_tables.get(node_name)
            if tt:
                mapped_nodes[node_name] = mapper.map_truth_table(tt)

        # Step 4: Aggregate Gate Breakdown & Transistor Cost
        gate_breakdown: Dict[str, int] = {}
        
        # Add Flip-Flops
        for reg in dag.registers.values():
            ff_type = "DFFR" if reg.reset_signal else "DFF"
            gate_breakdown[ff_type] = gate_breakdown.get(ff_type, 0) + reg.width

        # Add mapped gates
        for mn in mapped_nodes.values():
            for g, cnt in mn.gate_counts.items():
                gate_breakdown[g] = gate_breakdown.get(g, 0) + cnt

        total_gates = sum(gate_breakdown.values())
        total_transistors = sum(cnt * TRANSISTOR_COST.get(g, 6) for g, cnt in gate_breakdown.items())

        # Step 5: Emit Deliverables (Verilog-A & Virtuoso SKILL)
        va_emitter = VerilogAEmitter(dag, mapped_nodes, self.supply_voltage, self.threshold_voltage)
        veriloga_code = va_emitter.emit()

        skill_emitter = SKILLEmitter(dag, mapped_nodes, self.skill_lib)
        skill_code = skill_emitter.emit()

        # Step 6: Generate BOM Report
        bom_lines = [
            f"# Schematic Bill of Materials (BOM) for `{dag.module_name}`",
            f"",
            f"**Generated by AMS Digital Optimizer (Multi-Level DAG Engine)**",
            f"",
            f"| Standard Cell | Count | Est. Transistors / Cell | Total Transistors |",
            f"| :--- | :---: | :---: | :---: |",
        ]
        for g, cnt in sorted(gate_breakdown.items()):
            cost_per = TRANSISTOR_COST.get(g, 6)
            bom_lines.append(f"| `{g}` | {cnt} | {cost_per}T | {cnt * cost_per}T |")
        bom_lines.append(f"| **TOTAL** | **{total_gates} gates** | — | **~{total_transistors}T** |")
        bom_lines.append(f"")
        bom_lines.append(f"### Simplified Multi-Level Expressions")
        bom_lines.append(f"```verilog")
        for node_name in dag.topo_order:
            mn = mapped_nodes.get(node_name)
            if mn:
                bom_lines.append(f"  {node_name:<24} = {mn.expression};")
        bom_lines.append(f"```")
        bom_report = "\n".join(bom_lines)

        return OptimizationResult(
            module_name=dag.module_name,
            dag=dag,
            mapped_nodes=mapped_nodes,
            veriloga_code=veriloga_code,
            skill_code=skill_code,
            bom_report=bom_report,
            gate_breakdown=gate_breakdown,
            total_gates=total_gates,
            total_transistors=total_transistors,
        )
