"""Cadence Spectre Verilog-A Code Emitter.

Generates self-contained, 100% Cadence Spectre-compliant Verilog-A (.va) models
with embedded analog gate functions, topological multi-level intermediate net
evaluations, @(cross) register sampling, and continuous electrical voltage transitions.

Includes detailed circuit complexity notes (gate count, inverter equivalents GE,
and transistor breakdown) directly in the Verilog-A module header.

Zero external dependencies. Compatible with Python 3.9+.
"""

from __future__ import annotations
import re
from typing import Dict, List, Set

from .models import (
    SlicedDAG,
    SlicedPort,
    SlicedRegister,
    MappedLogicNode,
    TRANSISTOR_COST,
    INVERTER_EQUIVALENTS,
)


class VerilogAEmitter:
    """Generates Cadence Spectre-compliant Verilog-A code from mapped DAG logic."""

    def __init__(
        self,
        dag: SlicedDAG,
        mapped_nodes: Dict[str, MappedLogicNode],
        gate_breakdown: Dict[str, int],
        supply_voltage: float = 1.8,
        threshold_voltage: float = 0.9,
    ):
        self.dag = dag
        self.mapped_nodes = mapped_nodes
        self.gate_breakdown = gate_breakdown
        self.supply_voltage = supply_voltage
        self.threshold_voltage = threshold_voltage

        self.total_gates = sum(gate_breakdown.values())
        self.total_ge = sum(cnt * INVERTER_EQUIVALENTS.get(g, 2.0) for g, cnt in gate_breakdown.items())
        self.total_transistors = sum(cnt * TRANSISTOR_COST.get(g, 6) for g, cnt in gate_breakdown.items())

    def emit(self) -> str:
        lines: List[str] = []
        mod_name = f"{self.dag.module_name}_va"

        # 1. Header with Inverter Equivalents & Complexity Notes
        lines.append('`include "constants.vams"')
        lines.append('`include "disciplines.vams"')
        lines.append("")
        lines.append(f"// ============================================================================")
        lines.append(f"// Module: {mod_name}")
        lines.append(f"// Generated by AMS Digital Optimizer (Multi-Level DAG Synthesis Engine)")
        lines.append(f"// Cadence Spectre & Virtuoso Compatible Verilog-A Model")
        lines.append(f"//")
        lines.append(f"// Circuit Complexity & Silicon Area Notes:")
        lines.append(f"//   - Total Gate Count         : {self.total_gates} cells")
        lines.append(f"//   - Inverter Equivalents (GE) : {self.total_ge:.1f} inverters (1 GE = 1 Inverter = 2 Transistors)")
        lines.append(f"//   - Est. Transistor Count    : ~{self.total_transistors} transistors")
        lines.append(f"//")
        lines.append(f"// Standard Cell Breakdown (Gate Counts & Inverter Weights):")
        for g, cnt in sorted(self.gate_breakdown.items()):
            ge_per = INVERTER_EQUIVALENTS.get(g, 2.0)
            tr_per = TRANSISTOR_COST.get(g, 4)
            lines.append(f"//   - {g:<8}: {cnt:>3} cells ({cnt * ge_per:>5.1f} inverters eq., {cnt * tr_per:>4} transistors)")
        lines.append(f"// ============================================================================")
        lines.append("")

        # 2. Port list
        port_names = list(self.dag.ports.keys())
        lines.append(f"module {mod_name} ({', '.join(port_names)});")

        # 3. Port declarations & electrical disciplines
        for p_name, p in self.dag.ports.items():
            if p.width > 1:
                range_str = f"[{p.msb}:{p.lsb}]"
                lines.append(f"  {p.direction} {range_str} {p_name};")
                lines.append(f"  electrical {range_str} {p_name};")
            else:
                lines.append(f"  {p.direction} {p_name};")
                lines.append(f"  electrical {p_name};")

        # 4. Parameters
        lines.append("")
        lines.append(f"  // Electrical Parameters")
        lines.append(f"  parameter real vhigh = {self.supply_voltage:.3f};")
        lines.append(f"  parameter real vlow  = 0.000;")
        lines.append(f"  parameter real vth   = {self.threshold_voltage:.3f};")
        lines.append(f"  parameter real tdel  = 30p;")
        lines.append(f"  parameter real trise = 30p;")
        lines.append(f"  parameter real tfall = 30p;")
        lines.append("")

        # 5. Embedded Analog Gate Functions
        lines.extend(self._emit_analog_functions())

        # 6. Internal Real Signal Declarations
        lines.append("  // Internal State & Combinational Signals")
        # Sequential register Q and D nets
        for r_name, r in self.dag.registers.items():
            for bit_i in range(r.width):
                b_var = f"{r_name}_{bit_i}" if r.width > 1 else r_name
                lines.append(f"  real {b_var}_q, {b_var}_d;")

        # Combinational logic nodes (intermediates and non-register outputs)
        declared_vars: Set[str] = set()
        for node_name, node in self.dag.nodes.items():
            if node.node_type == "register_d":
                continue
            base_name = node_name.split("[")[0]
            if base_name in self.dag.registers:
                continue
            safe_var = node_name.replace("[", "_").replace("]", "") + "_val"
            if safe_var not in declared_vars:
                lines.append(f"  real {safe_var};")
                declared_vars.add(safe_var)

        lines.append("")

        # 7. Analog Begin Block
        lines.append("  analog begin")

        # Initial step reset initialization
        lines.append('    @(initial_step("static", "ac")) begin')
        for r_name, r in self.dag.registers.items():
            for bit_i in range(r.width):
                b_var = f"{r_name}_{bit_i}" if r.width > 1 else r_name
                init_val = "vhigh" if ((r.reset_val >> bit_i) & 1) else "vlow"
                lines.append(f"      {b_var}_q = {init_val};")
        lines.append("    end")
        lines.append("")

        # Sequential Clock Sampling
        clk_sig = "clk"
        for r in self.dag.registers.values():
            clk_sig = r.clock_signal
            break

        lines.append(f"    // Sequential Register Bank Clock Edge Sampling")
        lines.append(f"    @(cross(V({clk_sig}) - vth, +1)) begin")
        for r_name, r in self.dag.registers.items():
            for bit_i in range(r.width):
                b_var = f"{r_name}_{bit_i}" if r.width > 1 else r_name
                lines.append(f"      {b_var}_q = ({b_var}_d > vth) ? vhigh : vlow;")
        lines.append("    end")
        lines.append("")

        # Multi-Level Combinational Logic Evaluation (in topological order)
        lines.append("    // Multi-Level Combinational Logic Evaluations")
        for node_name in self.dag.topo_order:
            node = self.dag.nodes.get(node_name)
            if not node:
                continue
            mapped = self.mapped_nodes.get(node_name)
            expr_str = self._format_veriloga_expr(mapped.expression if mapped else "0.0")

            if node.node_type == "register_d":
                d_var = node_name.replace("[", "_").replace("]", "")
                lines.append(f"    {d_var} = {expr_str};")
            else:
                base_name = node_name.split("[")[0]
                if base_name in self.dag.registers:
                    continue  # Register outputs driven by _q
                val_var = node_name.replace("[", "_").replace("]", "") + "_val"
                lines.append(f"    {val_var} = {expr_str};")

        lines.append("")

        # Output Voltage Transition Contributions
        lines.append("    // Analog Electrical Output Drivers")
        for p_name, p in self.dag.ports.items():
            if p.direction == "output":
                for b_name in p.bit_names:
                    b_var = b_name.replace("[", "_").replace("]", "")
                    base_name = b_name.split("[")[0]
                    if base_name in self.dag.registers:
                        driver_sig = f"{b_var}_q"
                    else:
                        driver_sig = f"{b_var}_val"
                    lines.append(f"    V({b_name}) <+ transition(({driver_sig} > vth) ? vhigh : vlow, tdel, trise, tfall);")

        lines.append("  end")
        lines.append("endmodule")
        lines.append("")

        return "\n".join(lines)

    def _sub_signal(self, target_expr: str, sig_name: str, replacement: str) -> str:
        pattern = rf"(?<![A-Za-z0-9_]){re.escape(sig_name)}(?![A-Za-z0-9_])"
        return re.sub(pattern, replacement, target_expr)

    def _format_veriloga_expr(self, expr: str) -> str:
        """Formats gate expressions with analog voltages V(pin) and _q / _val variables."""
        # 1. Replace primary inputs with V(pin)
        for p in self.dag.primary_inputs:
            expr = self._sub_signal(expr, p, f"V({p})")

        # 2. Replace register references with their sampled state _q
        for r_name, r in self.dag.registers.items():
            for bit_i in range(r.width):
                b_name = f"{r_name}[{bit_i}]" if r.width > 1 else r_name
                b_var = f"{r_name}_{bit_i}_q" if r.width > 1 else f"{r_name}_q"
                expr = self._sub_signal(expr, b_name, b_var)

        # 3. Replace intermediate and output node dependencies with their _val variable
        for n_name, n in self.dag.nodes.items():
            if n.node_type == "register_d":
                continue
            base_name = n_name.split("[")[0]
            if base_name not in self.dag.registers:
                n_var = n_name.replace("[", "_").replace("]", "") + "_val"
                expr = self._sub_signal(expr, n_name, n_var)

        return expr

    def _emit_analog_functions(self) -> List[str]:
        """Emits embedded analog gate functions."""
        return [
            "  // Analog Standard Cell Helper Functions",
            "  analog function real INV;",
            "    input a; real a;",
            "    INV = !(a > vth) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real NAND2;",
            "    input a, b; real a, b;",
            "    NAND2 = !((a > vth) && (b > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real AND2;",
            "    input a, b; real a, b;",
            "    AND2 = ((a > vth) && (b > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real NOR2;",
            "    input a, b; real a, b;",
            "    NOR2 = !((a > vth) || (b > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real OR2;",
            "    input a, b; real a, b;",
            "    OR2 = ((a > vth) || (b > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real XOR2;",
            "    input a, b; real a, b;",
            "    XOR2 = ((a > vth) != (b > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real XNOR2;",
            "    input a, b; real a, b;",
            "    XNOR2 = ((a > vth) == (b > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real MUX2;",
            "    input s, d0, d1; real s, d0, d1;",
            "    MUX2 = (s > vth) ? d1 : d0;",
            "  endfunction",
            "",
            "  analog function real AOI21;",
            "    input a, b, c; real a, b, c;",
            "    AOI21 = !(((a > vth) && (b > vth)) || (c > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real OAI21;",
            "    input a, b, c; real a, b, c;",
            "    OAI21 = !(((a > vth) || (b > vth)) && (c > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real NAND3;",
            "    input a, b, c; real a, b, c;",
            "    NAND3 = !((a > vth) && (b > vth) && (c > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real AND3;",
            "    input a, b, c; real a, b, c;",
            "    AND3 = ((a > vth) && (b > vth) && (c > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real NOR3;",
            "    input a, b, c; real a, b, c;",
            "    NOR3 = !((a > vth) || (b > vth) || (c > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real OR3;",
            "    input a, b, c; real a, b, c;",
            "    OR3 = ((a > vth) || (b > vth) || (c > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real NAND4;",
            "    input a, b, c, d; real a, b, c, d;",
            "    NAND4 = !((a > vth) && (b > vth) && (c > vth) && (d > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            "",
            "  analog function real AND4;",
            "    input a, b, c, d; real a, b, c, d;",
            "    AND4 = ((a > vth) && (b > vth) && (c > vth) && (d > vth)) ? 1.0 : 0.0;",
            "  endfunction",
            ""
        ]
