"""Verilog-A Code Generator for AMS Digital Blocks (Cadence Spectre Compliant)."""

from __future__ import annotations
import re
from typing import Dict, List, Set
from .ast_parser import ParsedModule, DFFRegister
from .library import Library
from .tree_collapser import CollapsedExpression

class VerilogAEmitter:
    """Generates complete, self-contained, simulation-ready Verilog-A views for Cadence Spectre."""

    def __init__(self, library: Library):
        self.library = library

    def emit(
        self,
        parsed: ParsedModule,
        reg_expressions: Dict[str, CollapsedExpression],
        out_expressions: Dict[str, CollapsedExpression],
        used_gates: Set[str],
    ) -> str:
        """Generate Cadence-compliant Verilog-A source code."""
        lines: List[str] = []

        # 1. Header & Standard Includes
        lines.append("// =============================================================================")
        lines.append(f"// Cadence Spectre Verilog-A Model for AMS Digital Block: {parsed.name}")
        lines.append("// Generated by AMS Digital Optimizer & Synthesizer")
        lines.append("// =============================================================================")
        lines.append('`include "constants.vams"')
        lines.append('`include "disciplines.vams"')
        lines.append("")

        # 2. Module Header & Port List
        all_port_names = list(parsed.ports.keys())
        lines.append(f"module {parsed.name}_va ({', '.join(all_port_names)});")
        lines.append("")

        # 3. Port Directions
        for pname, port in parsed.ports.items():
            if port.is_vector:
                lines.append(f"  {port.direction} [{port.msb}:{port.lsb}] {pname};")
            else:
                lines.append(f"  {port.direction} {pname};")
        lines.append("")

        # 4. Electrical Discipline Declarations (with vector width matching)
        for pname, port in parsed.ports.items():
            if port.is_vector:
                lines.append(f"  electrical [{port.msb}:{port.lsb}] {pname};")
            else:
                lines.append(f"  electrical {pname};")
        lines.append("")

        # 5. Technology, Voltage & Timing Parameters
        lines.append("  // ---------------------------------------------------------------------------")
        lines.append("  // Technology & Timing Parameters (Cadence Spectre Compliant)")
        lines.append("  // ---------------------------------------------------------------------------")
        lines.append(f"  parameter real vdd   = {self.library.supply_voltage};")
        lines.append(f"  parameter real vth   = {self.library.threshold_voltage};")
        lines.append("  parameter real tdel  = 10p; // Propagation delay")
        lines.append("  parameter real trise = 10p; // Output rise time")
        lines.append("  parameter real tfall = 10p; // Output fall time")
        lines.append("  parameter real vtol  = 0;   // Voltage tolerance for cross event")
        lines.append("  parameter real ttol  = 0;   // Time tolerance for cross event")
        lines.append("")

        # 6. Analog Functions for Used Standard Cell Gates
        lines.append("  // ---------------------------------------------------------------------------")
        lines.append("  // Custom Analog Standard Cell Gate Functions")
        lines.append("  // ---------------------------------------------------------------------------")
        for gate_name in sorted(used_gates):
            cell = self.library.get_cell(gate_name)
            if cell and cell.veriloga_func:
                for func_line in cell.veriloga_func.strip().splitlines():
                    lines.append(f"  {func_line}")
                lines.append("")

        # 7. Internal Real Variables (State & Interconnect)
        lines.append("  // ---------------------------------------------------------------------------")
        lines.append("  // Internal State & Combinational Variables")
        lines.append("  // ---------------------------------------------------------------------------")
        sanitized_reg_names = {}
        for reg in parsed.registers:
            san_name = self._sanitize_name(reg.name)
            sanitized_reg_names[reg.name] = san_name
            lines.append(f"  real {san_name}_q;")
            lines.append(f"  real {san_name}_d;")

        for out_name in out_expressions.keys():
            san_out = self._sanitize_name(out_name)
            lines.append(f"  real {san_out}_val;")
        lines.append("")

        # 8. Main Cadence Verilog-A Analog Block
        lines.append("  // ===========================================================================")
        lines.append("  // Analog Behavioral Block")
        lines.append("  // ===========================================================================")
        lines.append("  analog begin")

        # 8a. Initial Step: DC Operating Point & AC Initialization
        if parsed.registers:
            lines.append("    // -------------------------------------------------------------------------")
            lines.append("    // 1. Initial Step: DC Operating Point State Initialization")
            lines.append("    // -------------------------------------------------------------------------")
            lines.append('    @(initial_step("static", "ac")) begin')
            for reg in parsed.registers:
                san = sanitized_reg_names[reg.name]
                init_val = "1.0" if reg.rst_val == 1 else "0.0"
                lines.append(f"      {san}_q = {init_val};")
            lines.append("    end")
            lines.append("")

        # 8b. Sequential Clock Cross Event
        if parsed.registers:
            clk_sig = parsed.registers[0].clk_signal
            rst_sig = parsed.registers[0].rst_signal
            rst_active_low = parsed.registers[0].rst_active_low

            lines.append("    // -------------------------------------------------------------------------")
            lines.append("    // 2. Sequential Clock Cross Event (Register Updates)")
            lines.append("    // -------------------------------------------------------------------------")
            lines.append(f"    @(cross(V({clk_sig}) - vth, 1, vtol, ttol)) begin")
            if rst_sig:
                rst_cond = f"V({rst_sig}) < vth" if rst_active_low else f"V({rst_sig}) > vth"
                lines.append(f"      if ({rst_cond}) begin")
                for reg in parsed.registers:
                    san = sanitized_reg_names[reg.name]
                    init_val = "1.0" if reg.rst_val == 1 else "0.0"
                    lines.append(f"        {san}_q = {init_val};")
                lines.append("      end else begin")
                for reg in parsed.registers:
                    san = sanitized_reg_names[reg.name]
                    lines.append(f"        {san}_q = {san}_d;")
                lines.append("      end")
            else:
                for reg in parsed.registers:
                    san = sanitized_reg_names[reg.name]
                    lines.append(f"      {san}_q = {san}_d;")
            lines.append("    end")
            lines.append("")

        # 8c. Combinational Next-State & Output Cones (Evaluated continuously)
        lines.append("    // -------------------------------------------------------------------------")
        lines.append("    // 3. Combinational Logic Cones (Simplified & Tech-Mapped)")
        lines.append("    // -------------------------------------------------------------------------")
        # Next-state equations for DFFs
        for reg in parsed.registers:
            san = sanitized_reg_names[reg.name]
            expr_obj = reg_expressions.get(reg.name)
            if expr_obj:
                va_expr = self._convert_expr_to_va(expr_obj.nested_expr, parsed, sanitized_reg_names)
                lines.append(f"    // D-input for DFF {reg.name}:")
                lines.append(f"    {san}_d = {va_expr};")

        # Combinational output equations
        for out_name, expr_obj in out_expressions.items():
            san_out = self._sanitize_name(out_name)
            va_expr = self._convert_expr_to_va(expr_obj.nested_expr, parsed, sanitized_reg_names)
            lines.append(f"    // Output {out_name}:")
            lines.append(f"    {san_out}_val = {va_expr};")
        lines.append("")

        # 8d. Analog Output Contribution Drivers
        lines.append("    // -------------------------------------------------------------------------")
        lines.append("    // 4. Analog Output Drivers (Continuous Transition Filters)")
        lines.append("    // -------------------------------------------------------------------------")
        for pname, port in parsed.ports.items():
            if port.direction == "output":
                if port.is_vector:
                    for bit_idx in range(min(port.msb, port.lsb), max(port.msb, port.lsb) + 1):
                        bit_name = f"{pname}[{bit_idx}]"
                        if bit_name in sanitized_reg_names:
                            san = sanitized_reg_names[bit_name]
                            lines.append(f"    V({bit_name}) <+ transition({san}_q * vdd, tdel, trise, tfall);")
                        elif bit_name in out_expressions:
                            san_out = self._sanitize_name(bit_name)
                            lines.append(f"    V({bit_name}) <+ transition({san_out}_val * vdd, tdel, trise, tfall);")
                else:
                    if pname in sanitized_reg_names:
                        san = sanitized_reg_names[pname]
                        lines.append(f"    V({pname}) <+ transition({san}_q * vdd, tdel, trise, tfall);")
                    elif pname in out_expressions:
                        san_out = self._sanitize_name(pname)
                        lines.append(f"    V({pname}) <+ transition({san_out}_val * vdd, tdel, trise, tfall);")

        lines.append("  end")
        lines.append("")
        lines.append("endmodule")
        return "\n".join(lines)

    def _sanitize_name(self, name: str) -> str:
        """Convert Verilog identifier with brackets (q[0]) to valid C/Verilog-A identifier (q_0)."""
        return re.sub(r"[\[\]]", "_", name).strip("_")

    def _convert_expr_to_va(self, expr_str: str, parsed: ParsedModule, sanitized_reg_names: Dict[str, str]) -> str:
        """Wrap primary inputs with V(pin) and register signals with reg_q."""
        s = expr_str.replace("1'b1", "1.0").replace("1'b0", "0.0")

        # Replace register signals (sorted by length descending)
        for reg_name, san_name in sorted(sanitized_reg_names.items(), key=lambda x: len(x[0]), reverse=True):
            if "[" in reg_name:
                s = s.replace(reg_name, f"{san_name}_q")
            else:
                s = re.sub(rf"\b{re.escape(reg_name)}\b", f"{san_name}_q", s)

        # Replace primary inputs with V(pin)
        for pin in sorted(parsed.get_all_input_signals(), key=lambda x: len(x), reverse=True):
            if "[" in pin:
                s = s.replace(pin, f"V({pin})")
            else:
                s = re.sub(rf"\b{re.escape(pin)}\b", f"V({pin})", s)

        return s
